CREATE DATABASE CLIMA_MEGA;

USE CLIMA_MEGA;

CREATE TABLE CLIENTES(
    RUT_CLIENTE INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    TELEFONO INT(20) NOT NULL,
    DIRECCION VARCHAR(100) NOT NULL
    );

CREATE TABLE SERVICIOS(
    ID_SERV INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100) NOT NULL
    );

CREATE TABLE ESTADO(
    ID_ESTADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(10) NOT NULL
    );

CREATE TABLE CATALOGO(
    COD_PROD INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOM_PROD VARCHAR(50) NOT NULL,
    PRECIO INT NOT NULL
    );
        
CREATE TABLE COTIZACION(
    NUM_COTIZ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLIENTES_RUT INT,
    #INICIO CREACION DE FOREIGN KEY PARA EL RUT DEL CLIENTE#
    FOREIGN KEY (CLIENTES_RUT)
        REFERENCES CLIENTES(RUT_CLIENTE)
        ON DELETE CASCADE,
    #FIN#
    SERVICIOS_TIPO INT,
    #INICIO CREACION DE FOREIGN KEY PARA EL TIPO DE SERVICIO#
    FOREIGN KEY (SERVICIOS_TIPO)
        REFERENCES SERVICIOS(ID_SERV)
        ON DELETE CASCADE,
    #FIN#
    EMISION DATE NOT NULL,
    EXPIRACION DATE NOT NULL,
    TOTAL INT,
    PRECIO_SERV INT,
    ESTADO_ID INT,
    #INICIO CREACION DE FOREIGN KEY PARA EL TIPO DE SERVICIO#
    FOREIGN KEY (ESTADO_ID)
        REFERENCES ESTADO(ID_ESTADO)
        ON DELETE CASCADE
    #FIN#
    );

CREATE TABLE PROD_COTIZ(
    CATALOGO_COD INT,
    #INICIO CREACION DE FOREIGN KEY PARA EL CODIGO DEL CATALOGO#
    FOREIGN KEY (CATALOGO_COD)
        REFERENCES CATALOGO(COD_PROD)
        ON DELETE CASCADE,
    #FIN#
    COTIZACION_NUM INT,
    #INICIO CREACION DE FOREIGN KEY PARA EL NUMERO DE COTIZACION#
    FOREIGN KEY (COTIZACION_NUM)
        REFERENCES COTIZACION(NUM_COTIZ)
        ON DELETE CASCADE,
    #FIN#
    CANTIDAD INT NOT NULL
    );
    
CREATE TABLE VENTA(
    NUM_VENTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COTIZACION_NUM INT,
    #INICIO CREACION DE FOREIGN KEY PARA EL NUMERO DE COTIZACION#
    FOREIGN KEY (COTIZACION_NUM)
        REFERENCES COTIZACION(NUM_COTIZ)
        ON DELETE CASCADE
    #FIN#
    );    