# Generated by Django 2.2 on 2019-06-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=32)),
                ('apellido', models.CharField(max_length=32)),
                ('correo', models.CharField(max_length=32)),
                ('telefono', models.CharField(max_length=16)),
                ('direccion', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('numero_cotizacion', models.IntegerField(primary_key=True, serialize=False)),
                ('emision', models.DateTimeField(verbose_name='Fecha emision')),
                ('expiracion', models.DateTimeField(verbose_name='Fecha expiracion')),
                ('total', models.IntegerField()),
                ('precio_servicio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('numero_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('codigoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Catalogo')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Estado'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='rut_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Cliente'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Servicio'),
        ),
    ]
