# Generated by Django 2.2 on 2019-06-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
