# Generated by Django 2.2 on 2019-06-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20190610_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_venta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
